// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make GitVersion functionality")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersion("5.0.0.0")>]
[<assembly: AssemblyInformationalVersion("5.0.0-alpha.14+Branch.add-gitversion.Sha.291f58cc70aba6dd871cf18e66d2d88357e4f208")>]
[<assembly: AssemblyFileVersion("5.0.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Core Xml functionality"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.0.0"
    let [<Literal>] AssemblyInformationalVersion = "5.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0"
